algoritmo "ExibeSequencia"
// Disciplina   :  Lógica de Programação
// Professora   : Tatyane Calixto
// Descrição   : Exibe de 0 até N.
// Autor(a)    : Herberth Leão
// Data atual  : 22/09/2020
var
   n: inteiro
   contador: inteiro
inicio
   // Lê o número N.
   escreval("Digite o último número da sequência: ")
   leia(n)

   // Exibe a sequência de 0 (zero) a N (inclusive).
   para contador de 0 ate n faca
      escreva(contador, " ")
   fimpara
fimalgoritmo