algoritmo "Tabuada"
// Disciplina   :  Lógica de Programação
// Professora   : Tatyane Calixto 
// Descrição   : Exibe a tabuada do número fornecido.
// Autor(a)    : Herberth Leão
// Data atual  : 08/10/2020
var
   n: inteiro
   contador: inteiro
inicio
   escreva("Digite um número: ")
   leia(n)
   
   para contador de 0 ate 10 faca
      escreval(n, " * ", contador, " = ", n * contador)
   fimpara
fimalgoritmo